// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backMecatronic.Data;

#nullable disable

namespace backMecatronic.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260326210811_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backMecatronic.Models.Entities.CategoriaProducto", b =>
                {
                    b.Property<int>("IdCategoriaProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_categoria_producto");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCategoriaProducto"));

                    b.Property<string>("DescripcionCategoriaProducto")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion_categoria_producto");

                    b.Property<string>("NombreCategoriaProducto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre_categoria_producto");

                    b.HasKey("IdCategoriaProducto")
                        .HasName("pk_categoria_producto");

                    b.ToTable("categoria_producto", (string)null);
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("ApellidoCliente")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("apellido_cliente");

                    b.Property<string>("DireccionCliente")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("direccion_cliente");

                    b.Property<bool>("EstadoCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("estado_cliente");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_registro");

                    b.Property<int>("IdTipoDocumento")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_documento");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre_cliente");

                    b.Property<string>("NumeroDocumentoCliente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("numero_documento_cliente");

                    b.Property<string>("TelefonoCliente")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono_cliente");

                    b.HasKey("IdCliente")
                        .HasName("pk_cliente");

                    b.HasIndex("IdTipoDocumento")
                        .HasDatabaseName("ix_cliente_id_tipo_documento");

                    b.HasIndex("IdUsuario")
                        .IsUnique()
                        .HasDatabaseName("ix_cliente_id_usuario");

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Comprobante", b =>
                {
                    b.Property<int>("IdComprobante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_comprobante");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdComprobante"));

                    b.Property<bool>("AceptadaSunat")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("aceptada_sunat");

                    b.Property<bool>("Anulado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("anulado");

                    b.Property<string>("ClienteDenominacion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("cliente_denominacion")
                        .HasAnnotation("Relational:JsonPropertyName", "cliente_denominacion");

                    b.Property<string>("ClienteNumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cliente_numero_documento")
                        .HasAnnotation("Relational:JsonPropertyName", "cliente_numero_de_documento");

                    b.Property<int>("ClienteTipoDocumento")
                        .HasMaxLength(20)
                        .HasColumnType("int")
                        .HasColumnName("cliente_tipo_documento")
                        .HasAnnotation("Relational:JsonPropertyName", "cliente_tipo_de_documento");

                    b.Property<string>("Enlace")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("enlace");

                    b.Property<string>("EnlacePdf")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("enlace_pdf");

                    b.Property<string>("EnlaceXml")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("enlace_xml");

                    b.Property<bool>("EnviadoSunat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("enviado_sunat")
                        .HasAnnotation("Relational:JsonPropertyName", "enviar_automaticamente_a_la_sumat");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_emision");

                    b.Property<int>("IdOrdenServicio")
                        .HasColumnType("int")
                        .HasColumnName("id_orden_servicio");

                    b.Property<int>("IdTipoComprobante")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_comprobante")
                        .HasAnnotation("Relational:JsonPropertyName", "tipo_de_comprobante");

                    b.Property<int>("Moneda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("moneda")
                        .HasAnnotation("Relational:JsonPropertyName", "moneda");

                    b.Property<int>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("int")
                        .HasColumnName("numero")
                        .HasAnnotation("Relational:JsonPropertyName", "numero");

                    b.Property<string>("Operacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("operacion")
                        .HasAnnotation("Relational:JsonPropertyName", "operacion");

                    b.Property<decimal>("PorcentajeIgv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(18m)
                        .HasColumnName("porcentaje_igv")
                        .HasAnnotation("Relational:JsonPropertyName", "porcentaje_de_igv");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("serie")
                        .HasAnnotation("Relational:JsonPropertyName", "serie");

                    b.Property<decimal>("Total")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total")
                        .HasAnnotation("Relational:JsonPropertyName", "total");

                    b.Property<decimal>("TotalGravada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_gravada")
                        .HasAnnotation("Relational:JsonPropertyName", "total_gravada");

                    b.Property<decimal>("TotalIgv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_igv")
                        .HasAnnotation("Relational:JsonPropertyName", "total_igv");

                    b.HasKey("IdComprobante")
                        .HasName("pk_comprobante");

                    b.HasIndex("IdOrdenServicio")
                        .HasDatabaseName("ix_comprobante_id_orden_servicio");

                    b.HasIndex("IdTipoComprobante")
                        .HasDatabaseName("ix_comprobante_id_tipo_comprobante");

                    b.ToTable("comprobante", (string)null);
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.ComprobanteDetalle", b =>
                {
                    b.Property<int>("IdComprobanteDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_comprobante_detalle");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdComprobanteDetalle"));

                    b.Property<bool>("AnticipoRegularizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("anticipo_regularizacion")
                        .HasAnnotation("Relational:JsonPropertyName", "anticipo_regularizacion");

                    b.Property<decimal>("Cantidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(65,30)")
                        .HasDefaultValue(1m)
                        .HasColumnName("cantidad")
                        .HasAnnotation("Relational:JsonPropertyName", "cantidad");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("codigo")
                        .HasAnnotation("Relational:JsonPropertyName", "codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion")
                        .HasAnnotation("Relational:JsonPropertyName", "descripcion");

                    b.Property<int>("IdComprobante")
                        .HasColumnType("int")
                        .HasColumnName("id_comprobante");

                    b.Property<decimal>("Igv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("igv")
                        .HasAnnotation("Relational:JsonPropertyName", "igv");

                    b.Property<decimal>("PrecioUnitario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("precio_unitario")
                        .HasAnnotation("Relational:JsonPropertyName", "precio_unitario");

                    b.Property<decimal>("Subtotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("subtotal")
                        .HasAnnotation("Relational:JsonPropertyName", "subtotal");

                    b.Property<int>("TipoDeIgv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("tipo_de_igv")
                        .HasAnnotation("Relational:JsonPropertyName", "tipo_de_igv");

                    b.Property<decimal>("Total")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total")
                        .HasAnnotation("Relational:JsonPropertyName", "total");

                    b.Property<string>("UnidadDeMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("unidad_de_medida")
                        .HasAnnotation("Relational:JsonPropertyName", "unidad_de_medida");

                    b.Property<decimal>("ValorUnitario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("valor_unitario")
                        .HasAnnotation("Relational:JsonPropertyName", "valor_unitario");

                    b.HasKey("IdComprobanteDetalle")
                        .HasName("pk_detalle_comprobante");

                    b.HasIndex("IdComprobante")
                        .HasDatabaseName("ix_detalle_comprobante_id_comprobante");

                    b.ToTable("detalle_comprobante", (string)null);

                    b.HasAnnotation("Relational:JsonPropertyName", "items");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.DetalleOrdenProducto", b =>
                {
                    b.Property<int>("IdDetalleOP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_detalle_op");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDetalleOP"));

                    b.Property<decimal>("Cantidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(65,30)")
                        .HasDefaultValue(1m)
                        .HasColumnName("cantidad");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<int>("IdOrdenServicio")
                        .HasColumnType("int")
                        .HasColumnName("id_orden_servicio");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<decimal>("PrecioUnitario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("precio_unitario");

                    b.Property<decimal>("Subtotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("subtotal");

                    b.HasKey("IdDetalleOP")
                        .HasName("pk_detalle_orden_producto");

                    b.HasIndex("IdOrdenServicio")
                        .HasDatabaseName("ix_detalle_orden_producto_id_orden_servicio");

                    b.HasIndex("IdProducto")
                        .HasDatabaseName("ix_detalle_orden_producto_id_producto");

                    b.ToTable("detalle_orden_producto", (string)null);
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.DetallePedidoProducto", b =>
                {
                    b.Property<int>("IdDetallePP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_detalle_pp");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDetallePP"));

                    b.Property<int>("Cantidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("cantidad");

                    b.Property<int>("IdPedido")
                        .HasColumnType("int")
                        .HasColumnName("id_pedido");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<decimal>("PrecioUnitario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("precio_unitario");

                    b.Property<decimal>("Subtotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("subtotal");

                    b.HasKey("IdDetallePP")
                        .HasName("pk_detalle_pedido_producto");

                    b.HasIndex("IdPedido")
                        .HasDatabaseName("ix_detalle_pedido_producto_id_pedido");

                    b.HasIndex("IdProducto")
                        .HasDatabaseName("ix_detalle_pedido_producto_id_producto");

                    b.ToTable("detalle_pedido_producto", (string)null);
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.DetalleProforma", b =>
                {
                    b.Property<int>("IdDetalleProforma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_detalle_proforma");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDetalleProforma"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<int>("IdProforma")
                        .HasColumnType("int")
                        .HasColumnName("id_proforma");

                    b.Property<int?>("IdServicio")
                        .HasColumnType("int")
                        .HasColumnName("id_servicio");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("sub_total");

                    b.HasKey("IdDetalleProforma")
                        .HasName("pk_detalle_proforma");

                    b.HasIndex("IdProducto")
                        .HasDatabaseName("ix_detalle_proforma_id_producto");

                    b.HasIndex("IdProforma")
                        .HasDatabaseName("ix_detalle_proforma_id_proforma");

                    b.HasIndex("IdServicio")
                        .HasDatabaseName("ix_detalle_proforma_id_servicio");

                    b.ToTable("detalle_proforma", (string)null);
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.DetalleReservaServicio", b =>
                {
                    b.Property<int>("IdDetalleRS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_detalle_rs");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDetalleRS"));

                    b.Property<int>("Cantidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("cantidad");

                    b.Property<int>("IdReserva")
                        .HasColumnType("int")
                        .HasColumnName("id_reserva");

                    b.Property<int>("IdServicio")
                        .HasColumnType("int")
                        .HasColumnName("id_servicio");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("observaciones");

                    b.Property<decimal>("PrecioUnitario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("precio_unitario");

                    b.Property<decimal>("Subtotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("subtotal");

                    b.HasKey("IdDetalleRS")
                        .HasName("pk_detalle_reserva_servicio");

                    b.HasIndex("IdReserva")
                        .HasDatabaseName("ix_detalle_reserva_servicio_id_reserva");

                    b.HasIndex("IdServicio")
                        .HasDatabaseName("ix_detalle_reserva_servicio_id_servicio");

                    b.ToTable("detalle_reserva_servicio", (string)null);
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.DetalleTecnicoEspecialidad", b =>
                {
                    b.Property<int>("IdDetalleTE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_detalle_te");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDetalleTE"));

                    b.Property<int>("IdEspecialidad")
                        .HasColumnType("int")
                        .HasColumnName("id_especialidad");

                    b.Property<int>("IdTecnico")
                        .HasColumnType("int")
                        .HasColumnName("id_tecnico");

                    b.HasKey("IdDetalleTE")
                        .HasName("pk_detalle_tecnico_especialidad");

                    b.HasIndex("IdEspecialidad")
                        .HasDatabaseName("ix_detalle_tecnico_especialidad_id_especialidad");

                    b.HasIndex("IdTecnico")
                        .HasDatabaseName("ix_detalle_tecnico_especialidad_id_tecnico");

                    b.ToTable("detalle_tecnico_especialidad", (string)null);
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.DetalleVehiculoCliente", b =>
                {
                    b.Property<int>("IdDetalleVC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_detalle_vc");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDetalleVC"));

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_registro");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdVehiculo")
                        .HasColumnType("int")
                        .HasColumnName("id_vehiculo");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("observaciones");

                    b.HasKey("IdDetalleVC")
                        .HasName("pk_detalle_vehiculo_cliente");

                    b.HasIndex("IdCliente")
                        .HasDatabaseName("ix_detalle_vehiculo_cliente_id_cliente");

                    b.HasIndex("IdVehiculo")
                        .HasDatabaseName("ix_detalle_vehiculo_cliente_id_vehiculo");

                    b.ToTable("detalle_vehiculo_cliente", (string)null);
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Especialidad", b =>
                {
                    b.Property<int>("IdEspecialidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_especialidad");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEspecialidad"));

                    b.Property<string>("DescripcionEspecialidad")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion_especialidad");

                    b.Property<string>("NombreEspecialidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_especialidad");

                    b.HasKey("IdEspecialidad")
                        .HasName("pk_especialidad");

                    b.ToTable("especialidad", (string)null);
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.MarcaProducto", b =>
                {
                    b.Property<int>("IdMarcaProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_marca_producto");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMarcaProducto"));

                    b.Property<string>("DescripcionMarcaProducto")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion_marca_producto");

                    b.Property<bool>("EstadoMarcaProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("estado_marca_producto");

                    b.Property<string>("NombreMarcaProducto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre_marca_producto");

                    b.HasKey("IdMarcaProducto")
                        .HasName("pk_marca_producto");

                    b.ToTable("marca_producto", (string)null);
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.MarcaVehiculo", b =>
                {
                    b.Property<int>("IdMarcaVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_marca_vehiculo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMarcaVehiculo"));

                    b.Property<string>("DescripcionMarcaVehiculo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion_marca_vehiculo");

                    b.Property<string>("NombreMarcaVehiculo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre_marca_vehiculo");

                    b.HasKey("IdMarcaVehiculo")
                        .HasName("pk_marca_vehiculo");

                    b.ToTable("marca_vehiculo", (string)null);
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.MetodoPago", b =>
                {
                    b.Property<int>("IdMetodoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_metodo_pago");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMetodoPago"));

                    b.Property<string>("DescripcionMetodoPago")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion_metodo_pago");

                    b.Property<bool>("EstadoMetodoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("estado_metodo_pago");

                    b.Property<string>("NombreMetodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre_metodo_pago");

                    b.HasKey("IdMetodoPago")
                        .HasName("pk_metodo_pago");

                    b.ToTable("metodo_pago", (string)null);
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.ModeloVehiculo", b =>
                {
                    b.Property<int>("IdModeloVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_modelo_vehiculo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdModeloVehiculo"));

                    b.Property<string>("DescripcionModeloVehiculo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion_modelo_vehiculo");

                    b.Property<int>("IdMarcaVehiculo")
                        .HasColumnType("int")
                        .HasColumnName("id_marca_vehiculo");

                    b.Property<int>("IdTipoVehiculo")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_vehiculo");

                    b.Property<string>("NombreModeloVehiculo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre_modelo_vehiculo");

                    b.HasKey("IdModeloVehiculo")
                        .HasName("pk_modelo_vehiculo");

                    b.HasIndex("IdMarcaVehiculo")
                        .HasDatabaseName("ix_modelo_vehiculo_id_marca_vehiculo");

                    b.HasIndex("IdTipoVehiculo")
                        .HasDatabaseName("ix_modelo_vehiculo_id_tipo_vehiculo");

                    b.ToTable("modelo_vehiculo", (string)null);
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Movimiento", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_movimiento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMovimiento"));

                    b.Property<int>("Cantidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("referencia");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipo");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("unidad_medida");

                    b.HasKey("IdMovimiento")
                        .HasName("pk_movimiento");

                    b.HasIndex("IdProducto")
                        .HasDatabaseName("ix_movimiento_id_producto");

                    b.ToTable("movimiento", (string)null);
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Notificacion", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_notificacion");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdNotificacion"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<int?>("IdOrdenServicio")
                        .HasColumnType("int")
                        .HasColumnName("id_orden_servicio");

                    b.Property<int?>("IdPedido")
                        .HasColumnType("int")
                        .HasColumnName("id_pedido");

                    b.Property<int?>("IdReserva")
                        .HasColumnType("int")
                        .HasColumnName("id_reserva");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<bool>("Leido")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("leido");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("mensaje");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("titulo");

                    b.HasKey("IdNotificacion")
                        .HasName("pk_notificacion");

                    b.HasIndex("IdOrdenServicio")
                        .HasDatabaseName("ix_notificacion_id_orden_servicio");

                    b.HasIndex("IdPedido")
                        .HasDatabaseName("ix_notificacion_id_pedido");

                    b.HasIndex("IdReserva")
                        .HasDatabaseName("ix_notificacion_id_reserva");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("ix_notificacion_id_usuario");

                    b.ToTable("notificacion", (string)null);
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.OrdenServicio", b =>
                {
                    b.Property<int>("IdOrdenServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_orden_servicio");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdOrdenServicio"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("En Proceso")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_inicio");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int?>("IdPedido")
                        .HasColumnType("int")
                        .HasColumnName("id_pedido");

                    b.Property<int?>("IdProforma")
                        .HasColumnType("int")
                        .HasColumnName("id_proforma");

                    b.Property<int?>("IdReserva")
                        .HasColumnType("int")
                        .HasColumnName("id_reserva");

                    b.Property<int?>("IdTecnico")
                        .HasColumnType("int")
                        .HasColumnName("id_tecnico");

                    b.Property<int?>("IdVehiculo")
                        .HasColumnType("int")
                        .HasColumnName("id_vehiculo");

                    b.Property<int>("TipoItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("tipo_item");

                    b.Property<decimal>("Total")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total");

                    b.HasKey("IdOrdenServicio")
                        .HasName("pk_orden_servicio");

                    b.HasIndex("IdCliente")
                        .HasDatabaseName("ix_orden_servicio_id_cliente");

                    b.HasIndex("IdPedido")
                        .IsUnique()
                        .HasDatabaseName("ix_orden_servicio_id_pedido");

                    b.HasIndex("IdProforma")
                        .HasDatabaseName("ix_orden_servicio_id_proforma");

                    b.HasIndex("IdReserva")
                        .IsUnique()
                        .HasDatabaseName("ix_orden_servicio_id_reserva");

                    b.HasIndex("IdTecnico")
                        .HasDatabaseName("ix_orden_servicio_id_tecnico");

                    b.HasIndex("IdVehiculo")
                        .HasDatabaseName("ix_orden_servicio_id_vehiculo");

                    b.ToTable("orden_servicio", (string)null);
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pago");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_pago");

                    b.Property<int>("IdMetodoPago")
                        .HasColumnType("int")
                        .HasColumnName("id_metodo_pago");

                    b.Property<int>("IdOrdenServicio")
                        .HasColumnType("int")
                        .HasColumnName("id_orden_servicio");

                    b.Property<decimal>("Monto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("monto");

                    b.HasKey("IdPago")
                        .HasName("pk_pago");

                    b.HasIndex("IdMetodoPago")
                        .HasDatabaseName("ix_pago_id_metodo_pago");

                    b.HasIndex("IdOrdenServicio")
                        .HasDatabaseName("ix_pago_id_orden_servicio");

                    b.ToTable("pago", (string)null);
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pedido");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPedido"));

                    b.Property<string>("EstadoPedido")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pendiente")
                        .HasColumnName("estado_pedido");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_pedido");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<string>("ObservacionesPedido")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("observaciones_pedido");

                    b.Property<decimal>("TotalPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_pedido");

                    b.HasKey("IdPedido")
                        .HasName("pk_pedido");

                    b.HasIndex("IdCliente")
                        .HasDatabaseName("ix_pedido_id_cliente");

                    b.ToTable("pedido", (string)null);
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("DescripcionProducto")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion_producto");

                    b.Property<bool>("EstadoProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("estado_producto");

                    b.Property<int>("IdCategoriaProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_categoria_producto");

                    b.Property<int>("IdMarcaProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_marca_producto");

                    b.Property<int?>("IdProveedor")
                        .HasColumnType("int")
                        .HasColumnName("id_proveedor");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("imagen_url");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_producto");

                    b.Property<decimal>("PrecioProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("precio_producto");

                    b.HasKey("IdProducto")
                        .HasName("pk_producto");

                    b.HasIndex("IdCategoriaProducto")
                        .HasDatabaseName("ix_producto_id_categoria_producto");

                    b.HasIndex("IdMarcaProducto")
                        .HasDatabaseName("ix_producto_id_marca_producto");

                    b.HasIndex("IdProveedor")
                        .HasDatabaseName("ix_producto_id_proveedor");

                    b.ToTable("producto", (string)null);
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Proforma", b =>
                {
                    b.Property<int>("IdProforma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_proforma");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProforma"));

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_emision");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.HasKey("IdProforma")
                        .HasName("pk_proforma");

                    b.HasIndex("IdCliente")
                        .HasDatabaseName("ix_proforma_id_cliente");

                    b.ToTable("proforma", (string)null);
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Proveedor", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_proveedor");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProveedor"));

                    b.Property<string>("ContactoProveedor")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("contacto_proveedor");

                    b.Property<string>("CorreoProveedor")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("correo_proveedor");

                    b.Property<string>("DireccionProveedor")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("direccion_proveedor");

                    b.Property<bool>("EstadoProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("estado_proveedor");

                    b.Property<int?>("IdTipoDocumento")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_documento");

                    b.Property<string>("NombreProveedor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre_proveedor");

                    b.Property<string>("NumeroDocumentoProveedor")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("numero_documento_proveedor");

                    b.Property<string>("TelefonoProveedor")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono_proveedor");

                    b.HasKey("IdProveedor")
                        .HasName("pk_proveedor");

                    b.HasIndex("IdTipoDocumento")
                        .HasDatabaseName("ix_proveedor_id_tipo_documento");

                    b.ToTable("proveedor", (string)null);
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_reserva");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pendiente")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaProgramada")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_programada");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.HasKey("IdReserva")
                        .HasName("pk_reserva");

                    b.HasIndex("IdCliente")
                        .HasDatabaseName("ix_reserva_id_cliente");

                    b.ToTable("reserva", (string)null);
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("DescripcionRol")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion_rol");

                    b.Property<bool>("EstadoRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("estado_rol");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre_rol");

                    b.HasKey("IdRol")
                        .HasName("pk_rol");

                    b.ToTable("rol", (string)null);
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Servicio", b =>
                {
                    b.Property<int>("IdServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_servicio");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdServicio"));

                    b.Property<string>("DescripcionServicio")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion_servicio");

                    b.Property<int>("DuracionServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(60)
                        .HasColumnName("duracion_servicio");

                    b.Property<bool>("EstadoServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("estado_servicio");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("imagen_url");

                    b.Property<string>("NombreServicio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_servicio");

                    b.Property<decimal>("PrecioServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("precio_servicio");

                    b.HasKey("IdServicio")
                        .HasName("pk_servicio");

                    b.ToTable("servicio", (string)null);
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Stock", b =>
                {
                    b.Property<int>("IdStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_stock");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdStock"));

                    b.Property<int>("CantidadActual")
                        .HasColumnType("int")
                        .HasColumnName("cantidad_actual");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<int?>("StockMinimo")
                        .HasColumnType("int")
                        .HasColumnName("stock_minimo");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ubicacion");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("unidad_medida");

                    b.HasKey("IdStock")
                        .HasName("pk_stock");

                    b.HasIndex("IdProducto")
                        .IsUnique()
                        .HasDatabaseName("ix_stock_id_producto");

                    b.ToTable("stock", (string)null);
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Tecnico", b =>
                {
                    b.Property<int>("IdTecnico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tecnico");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTecnico"));

                    b.Property<string>("ApellidoEmpleado")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("apellido_empleado");

                    b.Property<string>("CargoEmpleado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cargo_empleado");

                    b.Property<string>("CorreoEmpleado")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("correo_empleado");

                    b.Property<string>("DireccionEmpleado")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("direccion_empleado");

                    b.Property<string>("DniEmpleado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("dni_empleado");

                    b.Property<bool>("EstadoEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("estado_empleado");

                    b.Property<DateTime>("FechaContratacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_contratacion");

                    b.Property<string>("NombreEmpleado")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre_empleado");

                    b.Property<string>("TelefonoEmpleado")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono_empleado");

                    b.HasKey("IdTecnico")
                        .HasName("pk_tecnico");

                    b.ToTable("tecnico", (string)null);
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.TipoComprobante", b =>
                {
                    b.Property<int>("IdTipoComprobante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_comprobante");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTipoComprobante"));

                    b.Property<string>("CodigoSunat")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("codigo_sunat");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdTipoComprobante")
                        .HasName("pk_tipo_comprobante");

                    b.ToTable("tipo_comprobante", (string)null);
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.TipoDocumento", b =>
                {
                    b.Property<int>("IdTipoDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_documento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTipoDocumento"));

                    b.Property<string>("DescripcionTipoDocumento")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion_tipo_documento");

                    b.Property<string>("NombreTipoDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre_tipo_documento");

                    b.HasKey("IdTipoDocumento")
                        .HasName("pk_tipo_documento");

                    b.ToTable("tipo_documento", (string)null);
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.TipoVehiculo", b =>
                {
                    b.Property<int>("IdTipoVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_vehiculo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTipoVehiculo"));

                    b.Property<string>("DescripcionTipoVehiculo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion_tipo_vehiculo");

                    b.Property<string>("NombreTipoVehiculo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre_tipo_vehiculo");

                    b.HasKey("IdTipoVehiculo")
                        .HasName("pk_tipo_vehiculo");

                    b.ToTable("tipo_vehiculo", (string)null);
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("ContrasenaUsuario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contrasena_usuario");

                    b.Property<string>("CorreoUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("correo_usuario");

                    b.Property<string>("DireccionUsuario")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("direccion_usuario");

                    b.Property<bool>("EstadoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("estado_usuario");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_registro");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_usuario");

                    b.Property<string>("ResetToken")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("reset_token");

                    b.Property<DateTime?>("ResetTokenExpiracion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("reset_token_expiracion");

                    b.Property<string>("TelefonoUsuario")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono_usuario");

                    b.HasKey("IdUsuario")
                        .HasName("pk_usuario");

                    b.HasIndex("IdRol")
                        .HasDatabaseName("ix_usuario_id_rol");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Vehiculo", b =>
                {
                    b.Property<int>("IdVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_vehiculo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdVehiculo"));

                    b.Property<int?>("AnioVehiculo")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("anio_vehiculo");

                    b.Property<string>("ColorVehiculo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("color_vehiculo");

                    b.Property<bool>("EstadoVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("estado_vehiculo");

                    b.Property<int>("IdModeloVehiculo")
                        .HasColumnType("int")
                        .HasColumnName("id_modelo_vehiculo");

                    b.Property<string>("PlacaVehiculo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("placa_vehiculo");

                    b.Property<string>("urlFotoVehiculo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("url_foto_vehiculo");

                    b.HasKey("IdVehiculo")
                        .HasName("pk_vehiculo");

                    b.HasIndex("IdModeloVehiculo")
                        .HasDatabaseName("ix_vehiculo_id_modelo_vehiculo");

                    b.ToTable("vehiculo", (string)null);
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Cliente", b =>
                {
                    b.HasOne("backMecatronic.Models.Entities.TipoDocumento", "TipoDocumento")
                        .WithMany("Clientes")
                        .HasForeignKey("IdTipoDocumento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cliente_tipo_documento_id_tipo_documento");

                    b.HasOne("backMecatronic.Models.Entities.Usuario", "Usuario")
                        .WithOne("Cliente")
                        .HasForeignKey("backMecatronic.Models.Entities.Cliente", "IdUsuario")
                        .HasConstraintName("fk_cliente_usuario_id_usuario");

                    b.Navigation("TipoDocumento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Comprobante", b =>
                {
                    b.HasOne("backMecatronic.Models.Entities.OrdenServicio", "OrdenServicio")
                        .WithMany("Comprobantes")
                        .HasForeignKey("IdOrdenServicio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comprobante_orden_servicio_id_orden_servicio");

                    b.HasOne("backMecatronic.Models.Entities.TipoComprobante", "TipoComprobante")
                        .WithMany("Comprobantes")
                        .HasForeignKey("IdTipoComprobante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comprobante_tipo_comprobante_id_tipo_comprobante");

                    b.Navigation("OrdenServicio");

                    b.Navigation("TipoComprobante");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.ComprobanteDetalle", b =>
                {
                    b.HasOne("backMecatronic.Models.Entities.Comprobante", "Comprobante")
                        .WithMany("Detalles")
                        .HasForeignKey("IdComprobante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_detalle_comprobante_comprobante_id_comprobante");

                    b.Navigation("Comprobante");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.DetalleOrdenProducto", b =>
                {
                    b.HasOne("backMecatronic.Models.Entities.OrdenServicio", "OrdenServicio")
                        .WithMany("Detalles")
                        .HasForeignKey("IdOrdenServicio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_detalle_orden_producto_orden_servicio_id_orden_servicio");

                    b.HasOne("backMecatronic.Models.Entities.Producto", "Producto")
                        .WithMany("DetallesOrdenServicio")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_detalle_orden_producto_producto_id_producto");

                    b.Navigation("OrdenServicio");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.DetallePedidoProducto", b =>
                {
                    b.HasOne("backMecatronic.Models.Entities.Pedido", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_detalle_pedido_producto_pedido_id_pedido");

                    b.HasOne("backMecatronic.Models.Entities.Producto", "Producto")
                        .WithMany("DetallesPedido")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_detalle_pedido_producto_producto_id_producto");

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.DetalleProforma", b =>
                {
                    b.HasOne("backMecatronic.Models.Entities.Producto", "Producto")
                        .WithMany("Detalles")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_detalle_proforma_producto_id_producto");

                    b.HasOne("backMecatronic.Models.Entities.Proforma", "Proforma")
                        .WithMany("Detalles")
                        .HasForeignKey("IdProforma")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_detalle_proforma_proforma_id_proforma");

                    b.HasOne("backMecatronic.Models.Entities.Servicio", "Servicio")
                        .WithMany("Detalles")
                        .HasForeignKey("IdServicio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_detalle_proforma_servicio_id_servicio");

                    b.Navigation("Producto");

                    b.Navigation("Proforma");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.DetalleReservaServicio", b =>
                {
                    b.HasOne("backMecatronic.Models.Entities.Reserva", "Reserva")
                        .WithMany("Detalles")
                        .HasForeignKey("IdReserva")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_detalle_reserva_servicio_reserva_id_reserva");

                    b.HasOne("backMecatronic.Models.Entities.Servicio", "Servicio")
                        .WithMany("DetalleReservas")
                        .HasForeignKey("IdServicio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_detalle_reserva_servicio_servicio_id_servicio");

                    b.Navigation("Reserva");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.DetalleTecnicoEspecialidad", b =>
                {
                    b.HasOne("backMecatronic.Models.Entities.Especialidad", "Especialidad")
                        .WithMany("DetallesTecnicoEspecialidad")
                        .HasForeignKey("IdEspecialidad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_detalle_tecnico_especialidad_especialidad_id_especialidad");

                    b.HasOne("backMecatronic.Models.Entities.Tecnico", "Tecnico")
                        .WithMany("DetallesTecnicoEspecialidad")
                        .HasForeignKey("IdTecnico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_detalle_tecnico_especialidad_tecnico_id_tecnico");

                    b.Navigation("Especialidad");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.DetalleVehiculoCliente", b =>
                {
                    b.HasOne("backMecatronic.Models.Entities.Cliente", "Cliente")
                        .WithMany("DetalleVehiculos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_detalle_vehiculo_cliente_cliente_id_cliente");

                    b.HasOne("backMecatronic.Models.Entities.Vehiculo", "Vehiculo")
                        .WithMany("DetalleClientes")
                        .HasForeignKey("IdVehiculo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_detalle_vehiculo_cliente_vehiculo_id_vehiculo");

                    b.Navigation("Cliente");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.ModeloVehiculo", b =>
                {
                    b.HasOne("backMecatronic.Models.Entities.MarcaVehiculo", "MarcaVehiculo")
                        .WithMany("Modelos")
                        .HasForeignKey("IdMarcaVehiculo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_modelo_vehiculo_marca_vehiculo_id_marca_vehiculo");

                    b.HasOne("backMecatronic.Models.Entities.TipoVehiculo", "TipoVehiculo")
                        .WithMany("Modelos")
                        .HasForeignKey("IdTipoVehiculo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_modelo_vehiculo_tipo_vehiculo_id_tipo_vehiculo");

                    b.Navigation("MarcaVehiculo");

                    b.Navigation("TipoVehiculo");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Movimiento", b =>
                {
                    b.HasOne("backMecatronic.Models.Entities.Producto", "Producto")
                        .WithMany("Movimientos")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimiento_producto_id_producto");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Notificacion", b =>
                {
                    b.HasOne("backMecatronic.Models.Entities.OrdenServicio", "OrdenServicio")
                        .WithMany("Notificaciones")
                        .HasForeignKey("IdOrdenServicio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_notificacion_orden_servicio_id_orden_servicio");

                    b.HasOne("backMecatronic.Models.Entities.Pedido", "Pedido")
                        .WithMany("Notificaciones")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_notificacion_pedido_id_pedido");

                    b.HasOne("backMecatronic.Models.Entities.Reserva", "Reserva")
                        .WithMany("Notificaciones")
                        .HasForeignKey("IdReserva")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_notificacion_reserva_id_reserva");

                    b.HasOne("backMecatronic.Models.Entities.Usuario", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notificacion_usuario_id_usuario");

                    b.Navigation("OrdenServicio");

                    b.Navigation("Pedido");

                    b.Navigation("Reserva");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.OrdenServicio", b =>
                {
                    b.HasOne("backMecatronic.Models.Entities.Cliente", "Cliente")
                        .WithMany("OrdenesServicio")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_orden_servicio_cliente_id_cliente");

                    b.HasOne("backMecatronic.Models.Entities.Pedido", "Pedido")
                        .WithOne("OrdenServicio")
                        .HasForeignKey("backMecatronic.Models.Entities.OrdenServicio", "IdPedido")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_orden_servicio_pedido_id_pedido");

                    b.HasOne("backMecatronic.Models.Entities.Proforma", "Proforma")
                        .WithMany("OrdenesServicio")
                        .HasForeignKey("IdProforma")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_orden_servicio_proforma_id_proforma");

                    b.HasOne("backMecatronic.Models.Entities.Reserva", "Reserva")
                        .WithOne("OrdenServicio")
                        .HasForeignKey("backMecatronic.Models.Entities.OrdenServicio", "IdReserva")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_orden_servicio_reserva_id_reserva");

                    b.HasOne("backMecatronic.Models.Entities.Tecnico", "Tecnico")
                        .WithMany("OrdenServicios")
                        .HasForeignKey("IdTecnico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_orden_servicio_tecnico_id_tecnico");

                    b.HasOne("backMecatronic.Models.Entities.Vehiculo", "Vehiculo")
                        .WithMany("OrdenServicios")
                        .HasForeignKey("IdVehiculo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_orden_servicio_vehiculo_id_vehiculo");

                    b.Navigation("Cliente");

                    b.Navigation("Pedido");

                    b.Navigation("Proforma");

                    b.Navigation("Reserva");

                    b.Navigation("Tecnico");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Pago", b =>
                {
                    b.HasOne("backMecatronic.Models.Entities.MetodoPago", "MetodoPago")
                        .WithMany("Pagos")
                        .HasForeignKey("IdMetodoPago")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pago_metodo_pago_id_metodo_pago");

                    b.HasOne("backMecatronic.Models.Entities.OrdenServicio", "OrdenServicio")
                        .WithMany("Pagos")
                        .HasForeignKey("IdOrdenServicio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pago_orden_servicio_id_orden_servicio");

                    b.Navigation("MetodoPago");

                    b.Navigation("OrdenServicio");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Pedido", b =>
                {
                    b.HasOne("backMecatronic.Models.Entities.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_cliente_id_cliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Producto", b =>
                {
                    b.HasOne("backMecatronic.Models.Entities.CategoriaProducto", "CategoriaProducto")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoriaProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_producto_categoria_producto_id_categoria_producto");

                    b.HasOne("backMecatronic.Models.Entities.MarcaProducto", "MarcaProducto")
                        .WithMany("Productos")
                        .HasForeignKey("IdMarcaProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_producto_marca_producto_id_marca_producto");

                    b.HasOne("backMecatronic.Models.Entities.Proveedor", "Proveedor")
                        .WithMany("Productos")
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_producto_proveedor_id_proveedor");

                    b.Navigation("CategoriaProducto");

                    b.Navigation("MarcaProducto");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Proforma", b =>
                {
                    b.HasOne("backMecatronic.Models.Entities.Cliente", "Cliente")
                        .WithMany("Proformas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_proforma_cliente_id_cliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Proveedor", b =>
                {
                    b.HasOne("backMecatronic.Models.Entities.TipoDocumento", "TipoDocumento")
                        .WithMany("Proveedores")
                        .HasForeignKey("IdTipoDocumento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_proveedor_tipo_documento_id_tipo_documento");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Reserva", b =>
                {
                    b.HasOne("backMecatronic.Models.Entities.Cliente", "Cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reserva_cliente_id_cliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Stock", b =>
                {
                    b.HasOne("backMecatronic.Models.Entities.Producto", "Producto")
                        .WithOne("Stock")
                        .HasForeignKey("backMecatronic.Models.Entities.Stock", "IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stock_producto_id_producto");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Usuario", b =>
                {
                    b.HasOne("backMecatronic.Models.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_rol_id_rol");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Vehiculo", b =>
                {
                    b.HasOne("backMecatronic.Models.Entities.ModeloVehiculo", "ModeloVehiculo")
                        .WithMany("Vehiculos")
                        .HasForeignKey("IdModeloVehiculo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehiculo_modelo_vehiculo_id_modelo_vehiculo");

                    b.Navigation("ModeloVehiculo");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.CategoriaProducto", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Cliente", b =>
                {
                    b.Navigation("DetalleVehiculos");

                    b.Navigation("OrdenesServicio");

                    b.Navigation("Pedidos");

                    b.Navigation("Proformas");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Comprobante", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Especialidad", b =>
                {
                    b.Navigation("DetallesTecnicoEspecialidad");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.MarcaProducto", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.MarcaVehiculo", b =>
                {
                    b.Navigation("Modelos");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.MetodoPago", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.ModeloVehiculo", b =>
                {
                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.OrdenServicio", b =>
                {
                    b.Navigation("Comprobantes");

                    b.Navigation("Detalles");

                    b.Navigation("Notificaciones");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Pedido", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Notificaciones");

                    b.Navigation("OrdenServicio");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Producto", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("DetallesOrdenServicio");

                    b.Navigation("DetallesPedido");

                    b.Navigation("Movimientos");

                    b.Navigation("Stock")
                        .IsRequired();
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Proforma", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("OrdenesServicio");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Proveedor", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Reserva", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Notificaciones");

                    b.Navigation("OrdenServicio");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Servicio", b =>
                {
                    b.Navigation("DetalleReservas");

                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Tecnico", b =>
                {
                    b.Navigation("DetallesTecnicoEspecialidad");

                    b.Navigation("OrdenServicios");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.TipoComprobante", b =>
                {
                    b.Navigation("Comprobantes");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.TipoDocumento", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Proveedores");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.TipoVehiculo", b =>
                {
                    b.Navigation("Modelos");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Usuario", b =>
                {
                    b.Navigation("Cliente");

                    b.Navigation("Notificaciones");
                });

            modelBuilder.Entity("backMecatronic.Models.Entities.Vehiculo", b =>
                {
                    b.Navigation("DetalleClientes");

                    b.Navigation("OrdenServicios");
                });
#pragma warning restore 612, 618
        }
    }
}
